[package]
name = "ori"
version = "0.1.0"
edition.workspace = true

[workspace]
members = ["ori-gtk4", "ori-ike"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
ori      = { path = "."        }
ori-ike  = { path = "ori-ike"  }
ori-gtk4 = { path = "ori-gtk4" }
